name: "VcpkgPackage2"

# Test that the vcpkg package build successfully

on:
  workflow_dispatch:
  pull_request:
  push:


jobs:
  build:
    name: VcpkgPackage2
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-latest
            vcpkg_triplet: x64-linux-release
          - os: macos-latest
            vcpkg_triplet: x64-osx-release
          - os: windows-latest
            vcpkg_triplet: x64-windows-release


    steps:
      - name: install glfw & sdl requirements
        if : ${{ matrix.config.os == 'ubuntu-latest' }}
        shell: bash
        run: |
          sudo apt-get update && sudo apt-get install -y libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev pkg-config libx11-dev libxft-dev libxext-dev

#      - name: Install Vulkan Sdk Win
#        if: ${{ matrix.platform == 'windows-latest' }}
#        shell: powershell
#        run: |
#          Invoke-WebRequest -Uri "https://github.com/ocornut/imgui/files/3789205/vulkan-sdk-1.1.121.2.zip" -OutFile vulkan-sdk-1.1.121.2.zip
#          Expand-Archive -Path vulkan-sdk-1.1.121.2.zip
#          echo "VULKAN_SDK=$(pwd)\vulkan-sdk-1.1.121.2\" >>${env:GITHUB_ENV}
#
#      - name: Install Vulkan Sdk macOS
#        if: ${{ matrix.platform == 'macos-latest' }}
#        shell: bash
#        run: |
#          wget -q https://github.com/pthom/hello_imgui/releases/download/v1.0.0/VulkanSDK_1.3.268.1_macos.tgz
#          tar xfz VulkanSDK_1.3.268.1_macos.tgz
#          echo "VULKAN_SDK=$(pwd)/VulkanSDK/1.3.268.1/macOS" >> $GITHUB_ENV

      - name: vcpkg install
        uses: johnwason/vcpkg-action@v6
        id: vcpkg
        with:
          pkgs: 'nlohmann-json' # unrelated package, just to make the action happy
          triplet: ${{ matrix.config.vcpkg_triplet }}
          cache-key: ${{ matrix.config.os }}
          revision: master
          token: ${{ github.token }}
          github-binarycache: true

      - uses: actions/checkout@v4
        with:
          submodules: false

#      - name: Setup interactive tmate session
#        uses: mxschmitt/action-tmate@v3

      - name: all platforms - opengl3 and vulkan bindings
        shell: bash
        run: |
          # Test with opengl3-binding
          vcpkg install "hello-imgui[opengl3-binding, glfw-binding, sdl2-binding]" --overlay-ports=hello_imgui_cmake/overlay_vcpkg/hello-imgui --recurse
          vcpkg remove hello-imgui
          # Test with vulkan-binding
          vcpkg install "hello-imgui[vulkan-binding, glfw-binding, sdl2-binding]" --overlay-ports=hello_imgui_cmake/overlay_vcpkg/hello-imgui --recurse
          vcpkg remove hello-imgui

      - name: windows - directx bindings
        if : ${{ matrix.config.os == 'windows-latest' }}
        shell: bash
        run: |
          # Test with dx11-binding
          vcpkg install "hello-imgui[dx11-binding, glfw-binding, sdl2-binding]" --overlay-ports=hello_imgui_cmake/overlay_vcpkg/hello-imgui --recurse
          vcpkg remove hello-imgui
          # Test with vulkan-binding
          vcpkg install "hello-imgui[dx12-binding, glfw-binding, sdl2-binding]" --overlay-ports=hello_imgui_cmake/overlay_vcpkg/hello-imgui --recurse
          vcpkg remove hello-imgui

      - name: macos - metal bindings
        if : ${{ matrix.config.os == 'macos-latest' }}
        run: |
          # Test with metal-binding
          vcpkg install "hello-imgui[metal-binding, glfw-binding, sdl2-binding]" --overlay-ports=hello_imgui_cmake/overlay_vcpkg/hello-imgui --recurse
          vcpkg remove hello-imgui
