name: "VcpkgPackage"

# Test that the vcpkg package build successfully

on:
  workflow_dispatch:
  pull_request:
  push:


jobs:
  build:
    name: VcpkgPackage
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-latest
            vcpkg_triplet: x64-linux-release
          - os: macos-latest
            vcpkg_triplet: x64-osx-release
          - os: windows-latest
            vcpkg_triplet: x64-windows-release


    steps:
      - name: install glfw & sdl requirements
        if : ${{ matrix.config.os == 'ubuntu-latest' }}
        shell: bash
        run: |
          sudo apt-get update && sudo apt-get install -y libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev pkg-config libx11-dev libxft-dev libxext-dev

      - name: vcpkg install
        uses: johnwason/vcpkg-action@v6
        id: vcpkg
        with:
          pkgs: 'nlohmann-json' # unrelated package, just to make the action happy
          triplet: ${{ matrix.config.vcpkg_triplet }}
          cache-key: ${{ matrix.config.os }}
          revision: master
          token: ${{ github.token }}
          github-binarycache: true

      - uses: actions/checkout@v4
        with:
          submodules: false

#      - name: Setup interactive tmate session
#        uses: mxschmitt/action-tmate@v3

      - name: all platforms - opengl3 and vulkan bindings
        shell: bash
        run: |
          # Test with opengl3-binding
          vcpkg install "hello-imgui[opengl3-binding, glfw-binding, sdl2-binding]" --overlay-ports=hello_imgui_cmake/overlay_vcpkg/hello-imgui
          vcpkg remove hello-imgui
          # Test with vulkan-binding
          vcpkg install "hello-imgui[vulkan-binding, glfw-binding, sdl2-binding]" --overlay-ports=hello_imgui_cmake/overlay_vcpkg/hello-imgui
          vcpkg remove hello-imgui

      - name: windows - directx bindings
        if : ${{ matrix.config.os == 'windows-latest' }}
        shell: bash
        run: |
          # Test with dx11-binding
          vcpkg install "hello-imgui[dx11-binding, glfw-binding, sdl2-binding]" --overlay-ports=hello_imgui_cmake/overlay_vcpkg/hello-imgui
          vcpkg remove hello-imgui
          # Test with vulkan-binding
          vcpkg install "hello-imgui[dx12-binding, glfw-binding, sdl2-binding]" --overlay-ports=hello_imgui_cmake/overlay_vcpkg/hello-imgui
          vcpkg remove hello-imgui

      - name: macos - metal bindings
        if : ${{ matrix.config.os == 'windows-latest' }}
        run: |
          # Test with dx11-binding
          vcpkg install "hello-imgui[metal-binding, glfw-binding, sdl2-binding]" --overlay-ports=hello_imgui_cmake/overlay_vcpkg/hello-imgui
          vcpkg remove hello-imgui
